import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import '../styles';
import {ReactNode} from "react";

const inter = Inter({subsets:["latin"],preload:false});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <AppRouterCacheProvider>
                <body className={inter.className}>{children}</body>
            </AppRouterCacheProvider>
        </html>
    );
}
